a,b,c="Laptop",59999.99,True
print(a,b,c,sep=" ")
p,pr,av=input().split()
print("Product Name:",p)
print("Price",pr)
print("Availability",av)

a=int(input())
b=str(input())
c=float(input())
d=int(input())
e=float(input())
print(type(a))
print(type(b))
print(type(c))
print(type(d))
print(type(e))
