QUESTION 2
a=int(input("Employee ID:"))
b=int(input("Productivity:"))
c=int(input("Efficiency:"))
d=int(input("Reliability:"))
print("Employee Id:",a)
print("Productivity:",b)
print("Efficiency:",c)
print("Reliability:",d)
print("Performance Score:%.2f"%((b+c+d)/3))
